---
name: Deploy services to Okteto
on:
  push:
  schedule:
    - cron: 0 5 * * */2
jobs:
  deploy-to-okteto:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout code
        uses: actions/checkout@master
      - name: ➡️ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Note: this has been moved to the Dockerfile
      #- name: ➡️ Prepare backend environment
        #run: chmod +x github_actions_scripts/prepare-backend-environment.sh &&
        #  github_actions_scripts/prepare-backend-environment.sh
        #run: |
        #  python github_actions_scripts/prepare-backend-environment.py
      - name: ➡️ Create environment file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          # NOTE: Since I am using a database from Oracle Cloud,
          # and since they require it to be empty, I am passing
          # empty environment variables here. I was unable to set
          # completely empty GitHub Actions secrets.
          envkey_DATABASE_HOST: "" # ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: "" # ${{ secrets.DATABASE_PORT }}
          envkey_DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
          envkey_LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          envkey_LAST_FM_USER_AGENT: ${{ secrets.LAST_FM_USER_AGENT }}
          envkey_LAST_FM_USERNAME: ${{ secrets.LAST_FM_USERNAME }}
          envkey_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          envkey_SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          envkey_SPOTIFY_USER_AGENT: ${{ secrets.SPOTIFY_USER_AGENT }}
          envkey_FRONTEND_BASE_URL: ${{ secrets.FRONTEND_BASE_URL }}
          envkey_BASE_URL: ${{ secrets.BASE_URL }}
          envkey_BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
          envkey_ALBUM_OF_THE_DAY_BOT_TOKEN: ${{ secrets.ALBUM_OF_THE_DAY_BOT_TOKEN }}
          envkey_ALBUM_IMAGES_FONT_PATH: ${{ secrets.ALBUM_IMAGES_FONT_PATH }}
          envkey_DJANGO_CSRF_ORIGINS: ${{ secrets.DJANGO_CSRF_ORIGINS }}
          envkey_ORACLE_WALLET_FILE_CONTENTS: ${{ secrets.ORACLE_WALLET_FILE_CONTENTS }}
          envkey_ORACLE_SQLNET_FILE_CONTENTS: ${{ secrets.ORACLE_SQLNET_FILE_CONTENTS }}
          envkey_ORACLE_TNSNAMES_FILE_CONTENTS: ${{ secrets.ORACLE_TNSNAMES_FILE_CONTENTS }}
          envkey_TASK_RUNNER_CONFIG_FILE_CONTENTS: ${{ secrets.TASK_RUNNER_CONFIG_FILE_CONTENTS }}
          envkey_LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
          directory: website/backend/album_of_the_day_backend
          file_name: backend.env
      - name: Debug environment file
        run: |
          cd website
          cat ./backend/album_of_the_day_backend/backend.env
      - name: Deploy on Okteto
        run: |
          cd website
          ls
          curl https://get.okteto.com -sSfL | sh
          okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
          okteto deploy --build --loglevel debug
